### ISSUE TITLE
Problem with a first run

### ISSUE THREAD

**Issue by DROBNJAK** [StreamAlpha/tvdatafeed#1]
Hi StreamAlpha,

I copied the code from pypi.org to have a test run. I have Python v3.8.7 in VSC on Windows 7. The TradingView account I am accessing is paid and I can manually download .CSV files.

As expected code asked me to install Chrome driver where I answered: yes and y. Than I got this error report: 

(py_venv) PS C:\xxxx\Software\Python\Learning-00> python learn_TradingView_API.py

do you want to install chromedriver automatically??     yes

chromedriver not found. do you want to autoinstall chromedriver?? y/ny
Requirement already satisfied: chromedriver-autoinstaller in c:\xxxx\software\python\learning-00\py_venv\lib\site-packages (0.2.2)
WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the 'c:\xxxx\software\python\learning-00\py_venv\scripts\python.exe -m pip install --upgrade pip' command.

DevTools listening on ws://127.0.0.1:62801/devtools/browser/2f669919-1c01-4f9a-b6d1-d3a2a5578c51
[0515/185937.550:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is swiftshader
[0515/185952.124:INFO:CONSOLE(103)] "not loaded module js/expected-language", source: https://in.tradingview.com/static/bundles/category.97d1c8165098806fabf1.js (103)
[0515/190006.910:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190027.799:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190029.401:INFO:CONSOLE(291)] "2021-05-15T18:00:29.399Z:Fetch:POST //telemetry.tradingview.com/site-free/report. TypeError: Failed to fetch", source: https://in.tradingview.com/static/bundles/category.97d1c8165098806fabf1.js (291)
[0515/190029.405:INFO:CONSOLE(291)] "2021-05-15T18:00:29.400Z:Fetch:POST /accounts/signin/. TypeError: Failed to fetch", source: https://in.tradingview.com/static/bundles/category.97d1c8165098806fabf1.js (291)
[0515/190033.337:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190033.743:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190037.433:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190039.316:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190039.711:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190041.113:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190041.116:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190044.403:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190046.845:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190049.205:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190049.211:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190049.213:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190049.455:INFO:CONSOLE(311)] "not loaded module js/expected-language", source: https://www.tradingview.com/static/bundles/main_chart.a9f6daaaa0064d2db822.js (311)
[0515/190050.957:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190050.960:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190055.857:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190110.264:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190116.542:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190117.506:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190120.037:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190120.044:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190128.832:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190128.834:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190129.857:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
[0515/190129.859:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
error local variable 'token' referenced before assignment
~m~326~m~{"session_id":"<0.31858.145>_fra2-charts-6-webchart-9@fra2-compute-6_x","timestamp":1621101693,"release":"registry:5000/tvbs_release/webchart:release_204-36","studies_metadata_hash":"556d4eed209eaf4dd892a1acc52823e6e67d1b7c","protocol":"json","javastudies":"javastudies-3.60_1327","auth_scheme_vsn":2,"via":"84.16.251.31:443"}
~m~41~m~{"m":"protocol_error","p":["wrong data"]}

ERROR:tvDatafeed.main:Connection is already closed.
Traceback (most recent call last):
  File "learn_TradingView_API.py", line 65, in <module>
    nifty_data = objTV.get_hist(symbol='NIFTY',exchange='NSE',interval=Interval.in_1_hour,n_bars=1000)
  File "C:\xxxx\Software\Python\Learning-00\py_venv\lib\site-packages\tvDatafeed\main.py", line 328, in get_hist
    return self.__create_df(raw_data, symbol)
  File "C:\xxxx\Software\Python\Learning-00\py_venv\lib\site-packages\tvDatafeed\main.py", line 244, in __create_df
    out = re.search('"s":\[(.+?)\}\]', raw_data).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

What can possibly be wrong? Can you possibly suggest how to fix the above?

regards
DROBNJAK

**Comment by StreamAlpha** [comment]
temporarily fixed that, reinstall and you are good to go.
pip install --upgrade --no-cache-dir git+https://github.com/StreamAlpha/tvdatafeed.git@develop

**Comment by DROBNJAK** [comment]
Hey StreamAlpha

Thanks for the update!

Its really nifty library, pitty so few people know about it. Your video was really great.

I have few questions:

1) during the installation it failed to find a package ''. Should I install that package and re-install tvDatafeed?

2) I run my test code and it worked, but there was lots of chatter, like "handshake failed" etc. Is this normal: 

	> & "c:/Work D-PLUS-07/Software/Python/Learning-00/py_venv/Scripts/python.exe" "c:/Work D-PLUS-07/Software/Python/Learning-00/learn_TradingView_API.py"

	DevTools listening on ws://127.0.0.1:50766/devtools/browser/b8001b21-cc97-41d1-b76d-244695818516
	[0530/060421.368:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is swiftshader
	[0530/060454.110:INFO:CONSOLE(96)] "not loaded module js/expected-language", source: https://in.tradingview.com/static/bundles/category.3ea4d93c61fc0d3ebdb9.js (96)
	[0530/060514.956:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
	[0530/060518.028:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
	[0530/060518.033:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
	[0530/060518.102:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
	[0530/060518.105:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
	[0530/060518.147:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
	[0530/060518.151:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -101
	error Message: no such element: Unable to locate element: {"method":"css selector","selector":".tv-signin-dialog__toggle-email"}
	  (Session info: headless chrome=90.0.4430.212)

	                        symbol      open      high       low     close         volume
	datetime
	2020-10-28 03:30:00  NSE:NIFTY  11922.60  11929.40  11858.30  11886.40  1.000000e+100
	2020-10-28 04:30:00  NSE:NIFTY  11885.65  11902.45  11816.75  11816.90  1.000000e+100
	2020-10-28 05:30:00  NSE:NIFTY  11816.50  11857.70  11813.80  11848.60  1.000000e+100
	2020-10-28 06:30:00  NSE:NIFTY  11848.50  11861.45  11732.25  11750.30  1.000000e+100
	2020-10-28 07:30:00  NSE:NIFTY  11750.75  11776.70  11703.85  11709.80  1.000000e+100
	...                        ...       ...       ...       ...       ...            ...
	2021-05-28 06:30:00  NSE:NIFTY  15423.25  15437.00  15394.75  15433.25  1.000000e+100
	2021-05-28 07:30:00  NSE:NIFTY  15432.50  15444.00  15413.60  15435.40  1.000000e+100
	2021-05-28 08:30:00  NSE:NIFTY  15435.05  15469.65  15414.40  15463.85  1.000000e+100
	2021-05-28 09:30:00  NSE:NIFTY  15463.80  15466.25  15417.10  15417.15  1.000000e+100
	2021-05-28 10:30:00  NSE:NIFTY  15416.55  15458.35  15408.90  15435.65  1.000000e+100

	[1000 rows x 6 columns]

**Comment by StreamAlpha** [comment]
fixed in v1.0.3 develop
