### ISSUE TITLE
"OSError: [Errno 22] Invalid argument" only when downloading Daily Time Frame Data

### ISSUE THREAD

**Issue by raksmahesh** [StreamAlpha/tvdatafeed#101]
Thank you so much for the library!

Error I'm facing is:
It downloads data for intraday data for "TVC: DJI", but fails when downloading data for Daily Time Frame

Execution Output, Windows Command Prompt:

C:\Python\TradingView>python tvdatafeed.py
Downloading: TVC:DJI    for     Interval.in_1_minute
DJI-1m-20230103-20230210.csv     ...Done!

Downloading: TVC:DJI    for     Interval.in_5_minute
DJI-5m-20220808-20230210.csv     ...Done!

Downloading: TVC:DJI    for     Interval.in_15_minute
DJI-15m-20210802-20230210.csv    ...Done!

Downloading: TVC:DJI    for     Interval.in_1_hour
DJI-1h-20170103-20230210.csv     ...Done!

Downloading: TVC:DJI    for     Interval.in_daily
Traceback (most recent call last):
  File "C:\Python\TradingView\tvdatafeed.py", line 156, in <module>
    symbol_stock_data = tv.get_hist(symbol=SYMBOL,exchange=EXCH,interval=TIME,n_bars=20000)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raksm\AppData\Local\Programs\Python\Python311\Lib\site-packages\tvDatafeed\main.py", line 290, in get_hist
    return self.__create_df(raw_data, symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raksm\AppData\Local\Programs\Python\Python311\Lib\site-packages\tvDatafeed\main.py", line 143, in __create_df
    ts = datetime.datetime.fromtimestamp(float(xi[4]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument

Thank you so much!

**Comment by dart-bird** [comment]
This error occurs because the Unix timestamp represents a point in time relative to the Unix epoch (January 1, 1970), and negative timestamps represent a time before the epoch, which is outside the range of valid dates for the datetime module.
So... we can try this.
```python
timestamp = float(xi[4])
if timestamp < 0:
    ts = datetime.datetime(1970, 1, 1) + datetime.timedelta(seconds=(timestamp))
else:
    ts = datetime.datetime.fromtimestamp(timestamp)

```
it works. 👍🏻
