### ISSUE TITLE
Error thrown when downloading futures?

### ISSUE THREAD

**Issue by DROBNJAK** [StreamAlpha/tvdatafeed#15]
Hi,

Can you please check this error urgently? 

Delay going to cause me a huge gap in the data I am collecting.

About a week ago I downloaded 100s of symbols from TradingView. And even now I can download all the stocks, indices, etc. But suddenly it is refusing to download S&P 500 E-mini (ES1!, YM1!, etc.) and all the other futures, although it was downloading the same symbol just fine a week ago. Is it possible that TradingView changed the future symbols?

Please have a look: 

Exception has occured: AttributeError:
ERROR:tvDatafeed.main:Connection to remote host was lost.
Traceback (most recent call last):
  File "trade_1_download_dpALL_v0.00.py", line 269, in <module>
    dfDownloadedPricesTable = objTradingView.get_hist(symbol= symbol["symbol"], exchange= symbo
l["exchange"], interval= Interval.in_1_minute, n_bars= 5000)
  File "C:\Users\Dejan Corovic\.platformio\penv\lib\site-packages\tvDatafeed\main.py", line 334
, in get_hist
    return self.__create_df(raw_data, symbol)
  File "C:\Users\Dejan Corovic\.platformio\penv\lib\site-packages\tvDatafeed\main.py", line 250
, in __create_df
    out = re.search('"s":\[(.+?)\}\]', raw_data).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

regards,
DROBNJAK

**Comment by DROBNJAK** [comment]
False alarm. My bad, there was an error in my data.
