### ISSUE TITLE
PermissionError & UnboundLocalError: local variable 'driver' referenced before assignment

### ISSUE THREAD

**Issue by prathameshjoshi** [StreamAlpha/tvdatafeed#3]
i tried running first time and got following error. Also i have checked and changed permission as well but still getting same error
```
(tv) prathamesh@prathamesh-ThinkPad-X1-Carbon:~/Software/tvdatafeed-main$ python3 tv.py 

chromedriver not found. do you want to autoinstall chromedriver?? y/ny
Requirement already satisfied: chromedriver-autoinstaller in ./tv/lib/python3.8/site-packages (0.2.2)
error Message: '' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Traceback (most recent call last):
  File "/home/prathamesh/Software/tvdatafeed-main/tv/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/prathamesh/.tv_datafeed/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\tvDatafeed\main.py", line 89, in __get_token
  File "/home/prathamesh/Software/tvdatafeed-main/tv/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/prathamesh/Software/tvdatafeed-main/tv/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: '' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tv.py", line 8, in <module>
    tv=TvDatafeed(username, password, chromedriver_path=None)
  File "build\bdist.win-amd64\egg\tvDatafeed\main.py", line 176, in __init__
  File "build\bdist.win-amd64\egg\tvDatafeed\main.py", line 147, in __get_token
UnboundLocalError: local variable 'driver' referenced before assignment

```

**Comment by prathameshjoshi** [comment]
when i run python code file with 

> python3 tv.py

it changes permission. First i manually change permission of chrome driver but when i run code first time its overwrite permissions and changes it.

```
prathamesh@prathamesh-ThinkPad-X1-Carbon:~$ ls -al .tv_datafeed/
total 11316
drwxrwxrwx  2 prathamesh prathamesh     4096 May 25 22:10 .
drwxr-xr-x 95 prathamesh prathamesh    12288 May 26 22:19 ..
-rwxrwxrwx  1 prathamesh prathamesh 11569752 May 26 08:21 chromedriver
prathamesh@prathamesh-ThinkPad-X1-Carbon:~$ ls -al .tv_datafeed/
total 11472
drwxrwxrwx  2 prathamesh prathamesh     4096 May 25 22:10 .
drwxr-xr-x 95 prathamesh prathamesh    12288 May 26 22:19 ..
-rwxr--r--  1 prathamesh prathamesh 11728112 May 27 22:58 chromedriver

```

**Comment by prathameshjoshi** [comment]
First i downloaded chrome driver manually and stored in download folder. I added complete path in python script. 
`chromedriver_path='/home/xxx/Download/chromedriver/chromedriver`

This works without any error
