### ISSUE TITLE
Message: unknown error: Chrome failed to start: exited abnormally.   (unknown error: DevToolsActivePort file doesn't exist)

### ISSUE THREAD

**Issue by quantitative-technologies** [StreamAlpha/tvdatafeed#42]
The full error is below. Do you know what this means? Is it because I am using chromium instead of chrome? Or perhaps a firewall issue?

```
$ python historical_data.py 
INFO:tvDatafeed.main:refreshing tradingview token using selenium
DEBUG:tvDatafeed.main:launching chrome



You need to login manually

 Press 'enter' to open the browser 

opening browser. Press enter once lgged in return back and press 'enter'. 

DO NOT CLOSE THE BROWSER
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:55421/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "goog:loggingPrefs": {"performance": "ALL"}, "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": ["--disable-gpu", "--user-data-dir=/home/user/snap/chromium/common/chromium/Default"]}}}, "desiredCapabilities": {"browserName": "chrome", "goog:loggingPrefs": {"performance": "ALL"}, "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "args": ["--disable-gpu", "--user-data-dir=/home/user/snap/chromium/common/chromium/Default"]}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:55421
DEBUG:urllib3.connectionpool:http://localhost:55421 "POST /session HTTP/1.1" 500 365
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "/home/user/.virtualenvs/trading/lib/python3.7/site-packages/tvDatafeed/main.py", line 269, in __webdriver_init
    self.chromedriver_path, desired_capabilities=caps, options=options
  File "/home/user/.virtualenvs/trading/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/user/.virtualenvs/trading/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 99, in __init__
    options=options)
  File "/home/user/.virtualenvs/trading/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/user/.virtualenvs/trading/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/user/.virtualenvs/trading/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/user/.virtualenvs/trading/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/user/.tv_datafeed/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x650faa878e89 <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "historical_data.py", line 12, in <module>
    tv = TvDatafeed(auto_login=False)
  File "/home/user/.virtualenvs/trading/lib/python3.7/site-packages/tvDatafeed/main.py", line 145, in __init__
    token = self.auth(username, password)
  File "/home/user/.virtualenvs/trading/lib/python3.7/site-packages/tvDatafeed/main.py", line 220, in auth
    driver = self.__login(username, password)
  File "/home/user/.virtualenvs/trading/lib/python3.7/site-packages/tvDatafeed/main.py", line 160, in __login
    driver = self.__webdriver_init()
  File "/home/user/.virtualenvs/trading/lib/python3.7/site-packages/tvDatafeed/main.py", line 280, in __webdriver_init
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment
```

**Comment by StreamAlpha** [comment]
you need to use chrome. or since most of the data is available without logging in, you can use tvdatafeed without login. A working solution provided in link below

https://github.com/StreamAlpha/tvdatafeed/issues/26#issuecomment-912619033
