### ISSUE TITLE
Stocks and Indices OK, but Futures and Forex blow up

### ISSUE THREAD

**Issue by DROBNJAK** [StreamAlpha/tvdatafeed#6]
I am having problems downloading Futures and Forex. Stocks and Indices work fine. Here is the code:

I drilled down that problem is with the names of exchanges. For example for ES E-Mini exchange is CME_MINI, not CME. But the problem is FXCM forex exchange, the name is correct but the connection is refused. Do you possibly have a list of exchange tokens that TradingView's APIs are using?

# TEST: STOCKS ... OK
print('\n\n', 'MSFT-NASDAQ is OK.')
## print(dfTable)

# test: INDICES ... OK
print('\n\n', 'IMOEX-MOEX is OK.')
## print(dfTable)

# test: FUTURES ...  OK
## print(dfTable)

# TEST: FOREX ... fail
print('\n\n', 'EURGBP-FXCM fails?')
dfTable = objTV.get_hist(symbol= 'EURGBP', exchange= 'FXCM', interval= Interval.in_1_minute, n_bars=5000)
print(dfTable)

And here are the errors that I am getting: 

~m~328~m~{"session_id":"<0.5778.6401>_fra2-charts-32-webchart-6@fra2-compute-32_x","timestamp":1623721532,"release":"registry:5000/tvbs_release/webchart:release_204-36","studies_metadata_hash":"03f4e0fbdc9d0b595f5ee8037bed2288b28ccbdd","protocol":"json","javastudies":"javastudies-3.60_1327","auth_scheme_vsn":2,"via":"84.16.253.69:443"}
~m~82~m~{"m":"series_loading","p":["cs_prgbrtoohnho","s1","s1",1623721532],"t":1623721532}~m~74~m~{"m":"qsd","p":["qs_ugjmryrxsyxm",{"n":"FXCM:EURGBP","s":"error","v":{}}]}~m~98~m~{"m":"symbol_error","p":["cs_prgbrtoohnho","symbol_1","invalid symbol",1623721532],"t":1623721532}~m~140~m~{"m":"series_error","p":["cs_prgbrtoohnho","s1","s1","resolve error","fra2-charts-32-webchart-6@fra2-compute-32",1623721532],"t":1623721532}
~m~4~m~~h~1
~m~4~m~~h~2
~m~4~m~~h~3
~m~4~m~~h~4
~m~4~m~~h~5
~m~4~m~~h~6
~m~4~m~~h~7

ERROR:tvDatafeed.main:Connection is already closed.
Traceback (most recent call last):
  File "learn_TradingView_API_v1.00.py", line 87, in <module>
    dfTable = objTV.get_hist(symbol= 'EURGBP', exchange= 'FXCM', interval= Interval.in_1_minute, n_bars=5000)
  File "C:\Work D-PLUS-07\Software\Python\Learning-00\py_venv\lib\site-packages\tvDatafeed\main.py", line 333, in get_hist
    return self.__create_df(raw_data, symbol)
  File "C:\Work D-PLUS-07\Software\Python\Learning-00\py_venv\lib\site-packages\tvDatafeed\main.py", line 249, in __create_df
    out = re.search('"s":\[(.+?)\}\]', raw_data).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by DROBNJAK** [comment]
I found the solution.

FXCM exchange has the symbol FX. 

The best way to get symbols for exchanges is to set up a trade, and then in the top left corner of the trade placing form there is a symbol that's used for exchange.
